### ISSUE TITLE
不断提示“请求失败”，可是我就在同一台电脑上是可以获取 rss 内容的

### ISSUE THREAD

**Issue by TTtrace** [LJason77/bilibili-webhook#7]
选择的链接是：https://rsshub.app/bilibili/user/collection/316568752/981745

配置文件：
```toml
[[feed]]
# 订阅的源，来自 [RSSHub](https://github.com/DIYgod/RSSHub)
url = "https://rsshub.app/bilibili/user/collection/316568752/981745"
# 更新频率，单位：分钟
interval = 1
# yutto 的下载参数，具体可查看：[yutto](https://github.com/yutto-dev/yutto)
option = "--no-danmaku --proxy=no"
# 下载路径(相对路径)
path = "马督工"
# 是否更新，设为 false 即不更新
update = true
```

报错显示：

![image](https://github.com/LJason77/bilibili-webhook/assets/39454079/1276ba26-44cd-4b5d-84ec-8e79b0819a79)

而本地 curl 一下该链接地址是没问题的：

![image](https://github.com/LJason77/bilibili-webhook/assets/39454079/cd04629e-52b2-4729-8020-1f83bef71c91)
